### ISSUE TITLE
Add WalletLink support

### ISSUE THREAD

**Issue by nathang21** [pie-dao/pools.piedao.org#62]
#### Describe the ideal solution or feature request
Enable support for using [WalletLink](https://www.walletlink.org/#/) with the web3 PieDAO app. 

#### Who's asking?
Coinbase Wallet is a popular mobile wallet (that I use), that many other dApps have added support for via WalletLink.

**Comment by PierrickGT** [comment]
> #### Describe the ideal solution or feature request
> 
> Enable support for using [WalletLink](https://www.walletlink.org/#/) with the web3 PieDAO app. 
> 
> 
> 
> #### Who's asking?
> 
> Coinbase Wallet is a popular mobile wallet (that I use), that many other dApps have added support for via WalletLink. 

I've tried to connect using Coinbase Wallet and it did work.
Not sure we need WalletLink.

![image](https://user-images.githubusercontent.com/2401738/104816546-467f2b80-581c-11eb-886e-aa607424d3e4.png)

**Comment by nathang21** [comment]
Interesting, how did you manage that? When I click connect wallet I get these 2 options: 
- Metamask (N/A)
- WalletConnect (Error: Invalid QR code)

Neither of which let me QR scan from my Coinbase Wallet app.

**Comment by PierrickGT** [comment]
> Interesting, how did you manage that? When I click connect wallet I get these 2 options:
> 
> * Metamask (N/A)
> * WalletConnect (Error: Invalid QR code)
> 
> Neither of which let me QR scan from my Coinbase Wallet app.

Have you used the browser in the Coinbase Wallet app to connect?
I clicked on the top right connect button and didn't need to scan any QR Code on my desktop browser to connect.

**Comment by nathang21** [comment]
That did the trick, I could have sworn I tried that. Thanks.

Not sure how that worked but no login needed!
