### ISSUE TITLE
BAKE button should disappear from Pie pages when not available

### ISSUE THREAD

**Issue by dimarconicola** [pie-dao/pools.piedao.org#99]
On the individual Pie page we are showing a Bake button but it should be visible only if an oven for that specific Pie is available

**Comment by Alexintosh** [comment]
Some pies do not have an oven enabled.
The only ovens available are:

- PLAY
- DEFI++
- YPIE
- BCP
## Possible solution
Check in the oven config if the address matches:
https://github.com/pie-dao/pools.piedao.org/blob/development/src/config/ovensConf.js



![Screenshot 2021-06-03 at 12 47 49](https://user-images.githubusercontent.com/776519/120640045-54071c00-c472-11eb-8359-517b48ac1535.png)
